#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1892B42FCEAAEBC8 (sileht@redhat.com)
#
Name     : jsonpath-rw-ext
Version  : 1.0.0
Release  : 18
URL      : https://pypi.python.org/packages/source/j/jsonpath-rw-ext/jsonpath-rw-ext-1.0.0.tar.gz
Source0  : https://pypi.python.org/packages/source/j/jsonpath-rw-ext/jsonpath-rw-ext-1.0.0.tar.gz
Source99 : https://pypi.python.org/packages/source/j/jsonpath-rw-ext/jsonpath-rw-ext-1.0.0.tar.gz.asc
Summary  : Extensions for JSONPath RW
Group    : Development/Tools
License  : Apache-2.0
Requires: jsonpath-rw-ext-python
Requires: Babel
Requires: jsonpath-rw
Requires: pbr
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
===============================
python-jsonpath-rw-ext
===============================

%package python
Summary: python components for the jsonpath-rw-ext package.
Group: Default

%description python
python components for the jsonpath-rw-ext package.


%prep
%setup -q -n jsonpath-rw-ext-1.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489281563
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489281563
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
